### ISSUE TITLE
Fading time on jquery wordpress plugin

### ISSUE THREAD

**Issue by FalconX14** [dsawardekar/portkey#10]
Thanx for your great wp-lazy-load plugin.
I would like to know how to increase the fading time?

Also asked this here: https://wordpress.org/support/plugin/wp-lazy-load
But I thought you might not see it, as some other person asked the same 2 months ago.

Hope you have time to solve this question :-)

**Comment by dsawardekar** [comment]
@FalconX14 I've added the ability to control fade time in version 0.3.2.
