### ISSUE TITLE
Opening Fugitive splits produces an error

### ISSUE THREAD

**Issue by lluchs** [dsawardekar/portkey#5]
When opening a Fugitive split window, e.g. via `:Gdiff`, an error is shown:

```
Cannot load portkey: fugitive://[path to project]/.git//0/[path to the current file's directory]portkey.json
Press ENTER or type command to continue
```

The error reappears when focusing the split window.

**Comment by dsawardekar** [comment]
@lluchs I can't seem to replicate this on my setup. `:Gdiff`  and `:Gsplit` appear to work ok with Vim 7.4 p1-39, Ubuntu with latest Fugitive.

Can you post your `portkey.json`?

**Comment by lluchs** [comment]
Okay, thanks for testing. It also happened on portkey's repository, so it's probably caused by some other plugin. 

I'll report back when I have more information.

**Comment by lluchs** [comment]
It does indeed work with Vim 7.4. Thanks!

**Comment by razor-x** [comment]
I still get this issue in Neovim 0.7.1.

<a href="https://asciinema.org/a/45zuo5r7ody3wqjd49vxzpe55" target="_blank"><img src="https://asciinema.org/a/45zuo5r7ody3wqjd49vxzpe55.png" /></a>
